#pass ingress rules
 {{ if .Values.ingress.enabled | default false }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
spec:
  rules:
    - host: {{ .Values.ingress.hosts }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .Values.appName }}
                port:
                  number: {{ .Values.port }}

{{ end }}



